In [1]:
import json;
from pprint import pprint;
from sklearn.feature_extraction.text import TfidfVectorizer as tfidf;

In [2]:
def readFile(tweetsFile):
    fileHandle = open(tweetsFile, "r");
    data = json.load(fileHandle);
    fileHandle.close();
    length = len(data["statuses"]);
    tweets = [];
    for i in range(length):
        tweets.append(data["statuses"][i]["text"]);
    #print((data["statuses"][0]["text"]));
    return tweets;

In [3]:
print ("start");
tweetsFile = "smallsearch_output.txt";
tweets = readFile(tweetsFile);
print (type(tweets));
#pprint (tweets);

start
<type 'list'>


In [8]:
tweets[2]

u'RT @GOBERNATIA: Presidential Elections Dinner https://t.co/6B4hTPO93k 4 NOVIEMBRE en @ClubFinanciero #Madrid #USAElections @GOBERNATIA &amp; @i\u2026'

In [11]:
query = ["donald trump"]

In [12]:
corpus = query + tweets

In [16]:
len(corpus)
corpus[0]

'donald trump'

In [4]:
vectorizer = tfidf(min_df=1)

In [14]:
X = vectorizer.fit_transform(corpus)

In [6]:
idf = vectorizer.idf_
#print dict(zip(vectorizer.get_feature_names(), idf))

In [19]:
X[0:1]

<1x110 sparse matrix of type '<type 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.metrics.pairwise import linear_kernel

In [18]:
cosine_similarities = linear_kernel(X[0:1], X).flatten()

In [20]:
cosine_similarities

array([ 1.        ,  0.22777952,  0.25915375,  0.        ,  0.        ,
        0.27613407,  0.27613407,  0.27613407,  0.25915375,  0.        ,
        0.        ,  0.22777952,  0.22777952,  0.0872563 ,  0.        ,
        0.        ,  0.27613407,  0.27613407,  0.        ,  0.        ,
        0.27613407])

In [21]:
cosine_similarities.argsort()

array([10,  3,  4, 18,  9, 19, 14, 15, 13,  1, 11, 12,  2,  8, 17, 16, 20,
        6,  5,  7,  0], dtype=int64)

In [39]:
related_docs_indices = cosine_similarities.argsort()[:-12:-1]

In [40]:
related_docs_indices

array([ 0,  7,  5,  6, 20, 16, 17,  8,  2, 12, 11], dtype=int64)

In [32]:
related_docs_indices[3]

6

In [28]:
cosine_similarities[related_docs_indices]

array([ 1.        ,  0.27613407,  0.27613407,  0.27613407,  0.27613407,
        0.27613407,  0.27613407,  0.25915375,  0.25915375,  0.22777952,
        0.22777952])

In [31]:
type(related_docs_indices)

numpy.ndarray

In [43]:
for i in related_docs_indices[1:]:
    #print i
    #print (tweets[i-1])

IndentationError: expected an indented block (<ipython-input-43-c710b9fe1ca6>, line 3)

In [42]:
#tweets